version: '3.7'
services:
  my-cv-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: my-cv-back-end  
    working_dir: /usr/app/
    volumes:
      - /usr/app/node_modules/
      - .:/usr/app
      - .env.dev:/usr/app/.env.dev
    ports:
      - "3400:3400"
    networks: 
      - my-cv-services
    env_file:
      - .env.dev  
    command: ["npm","run","dev"] 

networks: 
  my-cv-services:
    external: true
    driver: bridge      

  